spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:payment
    username: sa
    password: 1111

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true # data script defer
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true